FROM gentoo/stage3 as builder

RUN cat <<EOF >> /etc/portage/make.conf
GENTOO_MIRRORS="https://ftp.lysator.liu.se/gentoo/"
FEATURES="-ipc-sandbox -network-sandbox -pid-sandbox"
EOF
RUN getuto && emerge-webrsync && emerge -j 5 -DNug @world

RUN echo 'sci-physics/lammps' >> /etc/portage/package.accept_keywords/all
RUN cat <<EOF > /etc/portage/package.use/lammps
sci-physics/lammps extra mpi opencl openmp python
sci-libs/netcdf mpi
sci-libs/hdf5 mpi
virtual/mpi romio
EOF
RUN emerge -j 5 -g lammps

RUN cat <<EOF > /etc/portage/package.use/python
dev-python/pillow webp
virtual/imagemagick-tools tiff jpeg
media-gfx/imagemagick tiff jpeg
dev-lang/python tk
EOF
RUN emerge -j 5 -DNug @world
RUN emerge -j 5 -g numpy matplotlib mpi4py scipy mypy black dev-python/pip

RUN emerge -c && rm -rf /var/db/repos && rm -rf /var/cache
FROM gentoo/stage3 as final
COPY --from=builder / /
